### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by levtelyatnikov** [lrnzgiusti/Simplicial-Attention-Networks#1]
What environment have you been using to run the code?

**Comment by lrnzgiusti** [comment]
I suggest revisiting the 'requirements.txt' file in the main folder, as it comprehensively outlines all necessary specifications and dependencies for the packages used in our environment, which may not have been fully explored due to an oversight.

To install Python dependencies using Conda from a requirements file, you can follow these steps:

If you do not already have Anaconda or Miniconda installed, download and install it from the official site. Anaconda is a distribution of Python for scientific computing, while Miniconda is a smaller, minimal version that includes only Conda and its dependencies.

1. Open a terminal (Command Prompt on Windows, Terminal app on macOS, or any terminal emulator on Linux).
2. Navigate to the directory containing the 'requirements.txt' file using the 'cd' command. For instance, if your file is in a directory named 'Simplicial-Attention-Networks' on your Desktop, you can navigate to it using the following command:
`cd ~/Desktop/Simplicial-Attention-Networks`
3. Once you are in the correct directory, you can create a new Conda environment and install the required packages with the following commands:
```bash
conda create --name san  python=3.9 
conda activate san 
```
4. use pip in the same environment to install the package:
```bash
pip install -r requirements.txt
```

This series of commands creates a new Conda environment, activates it, and then reads through the 'requirements.txt' file line by line, installing each package listed in the file. 

I hope this helps!
